/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/ubin108/efficientnet_xl.py", line 12, in <module>
    import albumentations as A
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/albumentations/augmentations/blur/functional.py", line 9, in <module>
    from albumentations.augmentations.geometric.functional import scale
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/albumentations/augmentations/geometric/__init__.py", line 1, in <module>
    from .functional import *
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/albumentations/augmentations/geometric/functional.py", line 6, in <module>
    import skimage.transform
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/skimage/transform/__init__.py", line 35, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/skimage/transform/hough_transform.py", line 2, in <module>
    from scipy.spatial import cKDTree
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/scipy/spatial/__init__.py", line 116, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/scipy/spatial/_geometric_slerp.py", line 9, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/scipy/spatial/distance.py", line 121, in <module>
    from ..special import rel_entr
  File "/home/ubin108/anaconda3/envs/jaeung/lib/python3.9/site-packages/scipy/special/__init__.py", line 798, in <module>
    from . import add_newdocs, basic, orthogonal, specfun, sf_error, spfun_stats
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 978, in get_code
  File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode
KeyboardInterrupt
